let maximo = max_int;; (*le dará a máximo el valor maximo en ocaml de los enteros (4611686018427387903)*)
let minimo = min_int;; (*le dará a mínimo el valor mínimo en ocaml de los enteros (-4611686018427387904)*)
minimo + maximo;; (*-1*)
minimo + maximo + 1;; (*0*)
maximo + 1;; (*No hay más datos con lo cual devolverá el valor mínimo porque da la vuelta*)
minimo = maximo + 1;; (*true*)
2 * minimo;; (*el valor minimo es -2^62 y si lo multiplicamos por 2 es -2^63 que no cabe con lo cual devuelve 0*)
minimo - 1 = maximo;; (*true*)
2 * maximo;; (*el valor maximo es 2^62 - 1 que si lo multiplicamos por 2  es (2^63-2) y 2⁶3 no cabe con lo cual devuelve -2*)
let maximo = 1. /. 0.;; (*le asigna el valor + infinito*)
let minimo = -1.0 /. 0.;; (*le asigna el valor - infinito*)
1. /. maximo;; (*1/infinito = 0*)
1. /. minimo;; (*1/ (- infinito) = -0*)
1. /. maximo = 1. /. minimo;; (*true*)
0. /. 0.;; (*indeterminado*)
maximo +. maximo;; (*infinito*)
maximo -. maximo;; (*indeterminado*)
-. maximo = minimo;; (*true*)
(*maximo + minimo;;*)(*Error de tipo puesto que se quiere sumar dos floats con el sumador int*)
not (minimo < maximo);; (*es true y con el not se convierte a false*)
let not = "no";;  (*Se le asigna a not el valor del string "no"*)
(*not (minimo < maximo)*);; (*Error de tipos puesto que not ahora es un string*)
Stdlib.not (minimo < maximo);; (*false*)
let not = "si" in not ^ not;; (*saca dos veces si*)
not;; (*saca no porque lo anterior no cambiaba el valor de not*)
(function x -> 2 * x);; (*se crea una funcion de int en int*)
(function x -> 2 * x) (2 + 1);; (*suma primero y despues hace la funcion 2*x (2*3 = 6)*)
(function x -> 2 * x) 2 + 1;; (*ejecuta la función solo aplicándola al 2 y luego le suma 1*)
(function y -> 2 * y) ((function y -> 2 * y) 3);; (*hace primero 2 * 3 y luego ese resultado lo multiplivca por 2 = 12*)
let doble = function z -> 2 * z;; (*Se le asigna a doble lo que hace la funcion*)
doble 2 + 1;; (*ejecuta la función solo aplicándola al 2 y luego le suma 1*)
doble (doble 3);; (*hace primero el doble de 3 y luego ese resultado lo dobla = 12*)
(*doble doble 3;;*) (*Error de ejecución puesto que va a intentar hacer el doble de doble*)
abs (1 - 2);; (*valor absoluto de -1 = 1*)
abs 1;; (*1*)
(*abs -1;;*) (*Error de tipo puesto que no tiene paréntesis y está intentando hacer una resta en vez de hacer al uno negativo*)
let abs = function x -> if x >= 0. then x else -. x;; (*funcion que asigna a abs que si x es mayor que 0 devuelva x y que sino la niegue*)
(*abs 1;;*) (*Error de tipo: ahora no funcionará porque la función es de tipo float*)
abs 1.5;; (*1.5*)
Stdlib.abs 1;; (*1*)
let suma = function (x,y) -> x + y;; (*Le asigna a la funcion suma que haga la suma entre dos numeros*)
2 * suma (2,3) - suma (1,1);; (*8*)
let sumac = function x -> (function y -> x + y);; (*Le asigna a la funcion sumac que haga *)
sumac 3;; (*no devolverá nada porque le falta una parte*)
(sumac 3) 2;; (*suma 3 + 2 = 5*)
sumac 3 2;; (*suma 2 + 3 = 5*)
suma (3,2) = sumac 3 2;; (*true*)
(*suma 3;;*) (*Error de ejecución porque suma necesita dos valores*)
let suma5 = sumac 5;; (*le asigna a suma5 el valor de hacer sumac 5*)
suma5 10;;(*le suma 10 a 5 = 15*)
let sumac x = function y -> x + y;; (*le asigna a sumac x la suma x + y*)
sumac 3 2;; (*5*)
let sumac x y = x + y;; (*le asigna a sumac x la suma x + y*)
sumac 3 2;; (*5*)